"""Initial migration

Revision ID: 39f19f6464fa
Revises: 
Create Date: 2024-04-11 16:12:42.162218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f19f6464fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('quote', sa.String(), nullable=True),
    sa.Column('grade_date', sa.Date(), nullable=True),
    sa.Column('signatures', sa.Integer(), nullable=True),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_students_cohort_id_cohorts')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
