"""Update Student model

Revision ID: 9730c489503a
Revises: 39f19f6464fa
Create Date: 2024-04-11 19:33:54.909583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9730c489503a'
down_revision = '39f19f6464fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grad_date', sa.Date(), nullable=True))
        batch_op.alter_column('signatures',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('grade_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_date', sa.DATE(), nullable=True))
        batch_op.alter_column('signatures',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('grad_date')

    # ### end Alembic commands ###
